# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envdiff < Formula
  desc "This tool prints envfile diff"
  homepage "https://github.com/yoskeoka/envdiff"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.4/envdiff_0.1.4_Darwin_x86_64"
      sha256 "e488390da73e354c616f84327976f5f44417bbb80dc60569738ad755b420aec8"

      def install
        bin.install "envdiff_0.1.4_Darwin_x86_64" => "envdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.4/envdiff_0.1.4_Darwin_arm64"
      sha256 "55a05fe45a52deeee9f5f0a067e8c37e468dfbcd5a9561f84ec1363dd43cbe3c"

      def install
        bin.install "envdiff_0.1.4_Darwin_arm64" => "envdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.4/envdiff_0.1.4_Linux_x86_64"
      sha256 "ceb203356d9bd312ad2f4daf23ce3f1262b7a10495e4f0f530fae12ab44bfb4b"

      def install
        bin.install "envdiff_0.1.4_Linux_x86_64" => "envdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.4/envdiff_0.1.4_Linux_arm64"
      sha256 "5310d488d5cb4e6fc4863925c8fe0ebcbc6b923289d87bf89e4b04c97a411746"

      def install
        bin.install "envdiff_0.1.4_Linux_arm64" => "envdiff"
      end
    end
  end

  test do
    system bin/"envdiff", "-version"
  end
end
