# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envdiff < Formula
  desc "This tool prints envfile diff"
  homepage "https://github.com/yoskeoka/envdiff"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.3/envdiff_0.1.3_Darwin_arm64"
      sha256 "58a4c30bc8f17bb9d0d45220da24a6af9972568c14906de10cfd37104bda3d0d"

      def install
        bin.install "envdiff_0.1.3_Darwin_arm64" => "envdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.3/envdiff_0.1.3_Darwin_x86_64"
      sha256 "3101cd132c60b3fb40db61252832bff2c1a646e67665e41039c3901ca23d446a"

      def install
        bin.install "envdiff_0.1.3_Darwin_x86_64" => "envdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.3/envdiff_0.1.3_Linux_arm64"
      sha256 "5eade970715b7bd450b44c9b53181fd80cb6a60f7cdf3c983961ac90bed1492d"

      def install
        bin.install "envdiff_0.1.3_Linux_arm64" => "envdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yoskeoka/envdiff/releases/download/v0.1.3/envdiff_0.1.3_Linux_x86_64"
      sha256 "ba9edb6f1ee9e759fb649f425532631b606eba38c1e4a0a9b93188058155d507"

      def install
        bin.install "envdiff_0.1.3_Linux_x86_64" => "envdiff"
      end
    end
  end

  test do
    system bin/"envdiff", "-version"
  end
end
